global:
  resolve_timeout: 1m

route:
  group_by: ['alertname']
  group_wait: 10s
  group_interval: 10s
  repeat_interval: 1m
  receiver: 'email'
  
receivers:
- name: 'email'
  email_configs:
  - to: 'to@example.com'
    from: 'from@example.com'
    smarthost: sandbox.smtp.mailtrap.io:587
    auth_username: 'd93a309c3894f2'
    auth_password: 'b3902d0c458c9d'
